[project]
name = "python-type-hint-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.19.0",
]
[tool.mypy]
strict = true                # 厳格モードを有効化
show_error_codes = true      # エラーコードを表示（原因特定に便利）
warn_unreachable = true      # 到達不能コードを警告

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
